### ISSUE TITLE
Test failing when run using Perl 5.18

### ISSUE THREAD

**Issue by atoomic** [muir/Text-Tabs-Wrap#8]
view output from https://github.com/atoomic/Text-Tabs-Wrap/runs/789428354?check_suite_focus=true

```
╰─> make test
PERL_DL_NONLAZY=1 /usr/bin/perl5.18 "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/37000.t ............ ok
t/39548.t ............ ok
t/79766.t ............ 1/2
#   Failed test 'This shouldn't happen at /System/Library/Perl/5.18/Text/Wrap.pm line 84.
# '
#   at t/79766.t line 18.

#   Failed test 'match'
#   at t/79766.t line 19.
#          got: undef
#     expected: 'xx xxxxxxxx xxxxxxxxx xx
# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx=xxxxxxxxxxxxx
# xxxxxxxxxxx'
# Looks like you failed 2 tests of 2.
t/79766.t ............ Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/2 subtests
t/belg4mit.t ......... ok
t/dandv.t ............ ok
t/dnsparks.t ......... skipped: not a regression test
t/fill.t ............. ok
t/Jacobson.t ......... ok
t/Jacobson2.t ........ ok
t/Jochen.t ........... ok
t/sep.t .............. ok
t/sep2.t ............. ok
t/Tabs-ElCid.t ....... ok
t/tabs.t ............. ok
t/Wrap-JLB.t ......... ok
t/wrap.t ............. ok
t/wrap_separator2.t .. ok

Test Summary Report
-------------------
t/79766.t          (Wstat: 512 Tests: 2 Failed: 2)
  Failed tests:  1-2
  Non-zero exit status: 2
Files=17, Tests=123,  0 wallclock secs ( 0.04 usr  0.03 sys +  0.15 cusr  0.06 csys =  0.28 CPU)
Result: FAIL
Failed 1/17 test programs. 2/123 subtests failed.
make: *** [test_dynamic] Error 255
```

This is not using the correct module version

**Comment by atoomic** [comment]
```
╰─> find ./blib/lib/
./blib/lib/
./blib/lib//auto
./blib/lib//auto/Text
./blib/lib//auto/Text/Wrap
./blib/lib//auto/Text/Wrap/.exists
./blib/lib//Text
./blib/lib//Text/.exists
./blib/lib//Text/Text
./blib/lib//Text/Text/Tabs.pm
./blib/lib//Text/Text/Wrap.pm
```

**Comment by ap** [comment]
Hi, [I’m the FIRSTCOME](https://metacpan.org/permission/distribution/Text-Tabs+Wrap) for this module and it’s now being maintained in [ap/Text-Tabs](/ap/Text-Tabs).

This whole version-switching mechanism is going away in the next release. I got [most of the way through a thorough cleanup](/ap/Text-Tabs/tree/next) two years ago but have been dragging my feet on the remainder ever since, mostly because a major part is licensing cleanup (make-)work. Sorry you wasted your time fixing it up because of that.

**Comment by ap** [comment]
(The interesting part should be the “remove ASCII-only codebase” commit, which I’m not linking directly because it’s on the `next` branch which I rebase freely.)

**Comment by atoomic** [comment]
@ap thanks for letting me know about the official repository for Text-Tabs.
I think it will be a good thing to update `Makefile.PL` to point to the accurate GitHub repository.
So metacpan could link to the correct repository.

You would have to update this line and perform a release
https://github.com/ap/Text-Tabs/blob/master/Makefile.PL#L14

This is great to hear you are working on a new version.
Do you have any estimation when this could be released?

The current published version fails to install on multiple version of Perl as showed by 
https://github.com/atoomic/Text-Tabs-Wrap/runs/789428354?check_suite_focus=true

I can see postponing to fix these issues if you are close to perform a release, otherwise I think we should consider patching the distribution and perform a release to fix them.

It appears that you closed all the pending Pull Requests I recently opened, including the addition of GitHub workflow for Continuous Integration. Would you be opened to some of these changes being submitted to https://github.com/ap/Text-Tabs ?

thanks for your understanding, waiting for your answers
sincerely
nicolas

**Comment by ap** [comment]
> It appears that you closed all the pending Pull Requests I recently opened, including the addition of GitHub workflow for Continuous Integration. Would you be opened to some of these changes being submitted to https://github.com/ap/Text-Tabs ?

And I thought you did, somehow, moments after I force-pushed to master in this repository to let people know where to go. But then I checked and found that GitHub credited those ticket closings to me, even though I didn’t ask for them. Apparently it somehow took the force-push as a signal that the PRs should be closed. I had no idea it would do that.

> I think it will be a good thing to update `Makefile.PL` to point to the accurate GitHub repository.

You saw that the metadata is already fixed in the `next` branch? But thank you for re-stating the obvious anyway. 🙂 It will happen in the next release. And in the meantime, this repository now points over to the new one, which fixes the problem even as long as MetaCPAN shows the wrong link. (I do wish we had some kind of PAUSE-based interface for this kind of metadata on CPAN, so that it wouldn’t require uploading a new release with zero actual changes…)

> Would you be opened to some of these changes being submitted to https://github.com/ap/Text-Tabs ?

Not particularly, I’ll admit. CPAN Testers already tells me that: http://matrix.cpantesters.org/?dist=Text-Tabs%2BWrap%202013.0523

> I can see postponing to fix these issues if you are close to perform a release, otherwise I think we should consider patching the distribution and perform a release to fix them.

The problem has already existed for over 7 years, or 5 years if you start counting from when I started dragging my feet. It’s not OK that this has been the case, and not OK for it to continue for years more, but it’s also clearly not urgent enough to warrant an emergency release that just digs the existing hole deeper. I should just get back to it and finish what I started.

**Comment by atoomic** [comment]
@ap IMO continuous integrations and CPAN Testers are both valuable but provide different informations:
- CI: helps you catching issues before a release
- CPAN Testers: helps you understand issues experienced by final users once released...

FYI I'm going to resubmit a few patches to your repository, as they are going to be required in the perl blead branch.

thanks for your help
